---
- name: Enable Percona 8
  shell: percona-release setup ps80

- name: Install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - percona-server-server
      - MySQL-python
      - mytop

- name: MySQL Config
  lineinfile:
    path: /etc/my.cnf
    line: 'default_authentication_plugin=mysql_native_password'
    state: present

- name: SystemD
  systemd:
    name: mysqld
    state: started
    enabled: yes
    daemon_reload: yes

- name: Find temporary password
  shell: >
    echo "$(cat /var/log/mysqld.log | grep temporary | cut -d ' ' -f 13 | xargs)"
  args:
    executable: /bin/bash
  register: mysql_root_password_temp

- name: Set /root/.my.cnf with temporary password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password_temp.stdout }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Update root password
  command: >
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
    --connect-expired-password
    -uroot
    -p"{{ mysql_root_password_temp.stdout }}"

- name: Set /root/my.cnf with actual password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Setup root mytop
  copy:
    content: |
      user=root
      pass={{ mysql_root_password }}
      host=localhost
      db=information_schema
      delay=5
      port=3306
      batchmode=0
      header=1
      color=1
      idle=1
    dest: /root/.mytop
    owner: root
    group: root
    mode: 0600

- name: Remove insecure stuff
  shell: >
    mysql  -NBe "
    DELETE FROM mysql.user WHERE User='';
    DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
    DROP DATABASE IF EXISTS test;
    DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
    FLUSH PRIVILEGES;
    "
    -uroot
    -p"{{ mysql_root_password }}"