---
- name: Enable Percona 8
  shell: percona-release setup ps80

- name: Install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - percona-server-server
      - MySQL-python
      - mytop

- name: MySQL Config
  lineinfile:
    path: /etc/my.cnf
    line: 'default_authentication_plugin=mysql_native_password'
    state: present

- name: SystemD
  systemd:
    name: mysqld
    state: started
    enabled: yes
    daemon_reload: yes

- name: Test if can connect as root
  shell: mysql -NBe "select 1" -u root -p{{ mysql_root_password }}
  register: can_connect
  ignore_errors: true

- include_tasks: set-root-password.yml
  when: can_connect is failed

- name: Setup root mytop
  copy:
    content: |
      user=root
      pass={{ mysql_root_password }}
      host=localhost
      db=information_schema
      delay=5
      port=3306
      batchmode=0
      header=1
      color=1
      idle=1
    dest: /root/.mytop
    owner: root
    group: root
    mode: 0600

- name: Remove insecure stuff
  shell: >
    mysql  -NBe "
    DELETE FROM mysql.user WHERE User='';
    DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
    DROP DATABASE IF EXISTS test;
    DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
    FLUSH PRIVILEGES;
    "
    -uroot
    -p"{{ mysql_root_password }}"