---
- name: Enable Percona 8
  shell: percona-release setup ps80

- name: Install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - percona-server-server
      - MySQL-python

- name: MySQL Config
  lineinfile:
    path: /etc/my.cnf
    line: 'default_authentication_plugin=mysql_native_password'
    state: present

- name: SystemD
  systemd:
    name: mysqld
    state: started
    enabled: yes
    daemon_reload: yes

- name: Find temporary password
  shell: >
    echo "$(cat /var/log/mysqld.log | grep temporary | cut -d ' ' -f 13 | xargs)"
  args:
    executable: /bin/bash
  register: mysql_root_password_temp

- name: Set /root/.my.cnf with temporary password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password_temp.stdout }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
#
#- name: Set new password from temporary password
#  mysql_user:
#    name: root
#    password: "{{ mysql_root_password }}"
#    encrypted: yes
#    host: localhost
#    state: present
#    login_user: root
#    login_password: "{{ mysql_root_password_temp.stdout }}"
#  run_once: true
- name: Update root password
  command: >
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
    --connect-expired-password
    -uroot
    -p"{{ mysql_root_password_temp.stdout }}"

- name: Set /root/my.cnf with actual password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
