
- name: Find temporary password
  shell: >
    echo "$(cat /var/log/mysqld.log | grep temporary | cut -d ' ' -f 13 | xargs)"
  args:
    executable: /bin/bash
  register: mysql_root_password_temp

- name: Set /root/.my.cnf with temporary password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password_temp.stdout }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Update root password
  command: >
    mysql
    --defaults-file=/root/.my.cnf
    --connect-expired-password
    -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"

- name: Set /root/my.cnf with actual password
  copy:
    content: |
      [client]
      user=root
      password="{{ mysql_root_password }}"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
